# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AF6Q4z6N6KUYtWK3CujwdEQOlaBeJMLB
"""

import math

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        return "Error! Division by zero."
    return x / y

def modulus(x, y):
    return x % y

def power(x, y):
    return math.pow(x, y)

def square_root(x):
    return math.sqrt(x)

def log_base_10(x):
    return math.log10(x)

def natural_log(x):
    return math.log(x)

def sine(x):
    return math.sin(math.radians(x))  # degrees to radians

def cosine(x):
    return math.cos(math.radians(x))

def tangent(x):
    return math.tan(math.radians(x))

def display_menu():
    print("\n=== SCIENTIFIC CALCULATOR ===")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")
    print("5. Modulus")
    print("6. Power (x^y)")
    print("7. Square Root")
    print("8. Log Base 10")
    print("9. Natural Log (ln)")
    print("10. Sine")
    print("11. Cosine")
    print("12. Tangent")
    print("13. Exit")

while True:
    display_menu()
    choice = input("Choose an operation (1-13): ")

    if choice == '13':
        print("Exiting calculator. Goodbye!")
        break

    try:
        if choice in ['1','2','3','4','5','6']:
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))

            if choice == '1':
                print("Result:", add(num1, num2))
            elif choice == '2':
                print("Result:", subtract(num1, num2))
            elif choice == '3':
                print("Result:", multiply(num1, num2))
            elif choice == '4':
                print("Result:", divide(num1, num2))
            elif choice == '5':
                print("Result:", modulus(num1, num2))
            elif choice == '6':
                print("Result:", power(num1, num2))

        elif choice in ['7','8','9','10','11','12']:
            num = float(input("Enter number: "))

            if choice == '7':
                print("Result:", square_root(num))
            elif choice == '8':
                print("Result:", log_base_10(num))
            elif choice == '9':
                print("Result:", natural_log(num))
            elif choice == '10':
                print("Result:", sine(num))
            elif choice == '11':
                print("Result:", cosine(num))
            elif choice == '12':
                print("Result:", tangent(num))
        else:
            print("Invalid choice. Please select between 1-13.")
    except ValueError:
        print("Invalid input! Please enter numeric values.")
    except Exception as e:
        print("Error:", str(e))