# -*- coding: utf-8 -*-
"""Project-2(Currency converter)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOrbt62m-tLFGijxey7huAz1z8EhXdu_
"""

def convert_currency(amount, from_currency, to_currency):
    # Static exchange rates (example as of June 2025)
    exchange_rates = {
        "USD": 1.0,
        "INR": 83.25,
        "EUR": 0.92,
        "GBP": 0.78,
        "JPY": 157.5,
        "AUD": 1.51
    }

    if from_currency not in exchange_rates or to_currency not in exchange_rates:
        return "Currency not supported."

    usd_amount = amount / exchange_rates[from_currency]
    converted = usd_amount * exchange_rates[to_currency]
    return round(converted, 2)


# Example usage
amount = float(input("Enter amount: "))
from_curr = input("From currency (e.g., USD, INR): ").upper()
to_curr = input("To currency (e.g., USD, INR): ").upper()

result = convert_currency(amount, from_curr, to_curr)
print(f"{amount} {from_curr} = {result} {to_curr}")